// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: system.proto

package server

import (
	"context"

	"github.com/bearllflee/scholar-track/rpc/system/internal/logic/casbin"
	"github.com/bearllflee/scholar-track/rpc/system/internal/svc"
	"github.com/bearllflee/scholar-track/rpc/system/system"
)

type CasbinServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedCasbinServer
}

func NewCasbinServer(svcCtx *svc.ServiceContext) *CasbinServer {
	return &CasbinServer{
		svcCtx: svcCtx,
	}
}

func (s *CasbinServer) AddPolicy(ctx context.Context, in *system.AddPolicyReq) (*system.AddPolicyResp, error) {
	l := casbinlogic.NewAddPolicyLogic(ctx, s.svcCtx)
	return l.AddPolicy(in)
}

func (s *CasbinServer) Enforce(ctx context.Context, in *system.EnforceReq) (*system.EnforceResp, error) {
	l := casbinlogic.NewEnforceLogic(ctx, s.svcCtx)
	return l.Enforce(in)
}
