// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: storage.proto

package server

import (
	"context"

	"github.com/bearllfleed/scholar-track/rpc/storage/internal/logic"
	"github.com/bearllfleed/scholar-track/rpc/storage/internal/svc"
	"github.com/bearllfleed/scholar-track/rpc/storage/storage"
)

type StorageServer struct {
	svcCtx *svc.ServiceContext
	storage.UnimplementedStorageServer
}

func NewStorageServer(svcCtx *svc.ServiceContext) *StorageServer {
	return &StorageServer{
		svcCtx: svcCtx,
	}
}

func (s *StorageServer) FileUpload(ctx context.Context, in *storage.FileUploadRequest) (*storage.FileUploadResponse, error) {
	l := logic.NewFileUploadLogic(ctx, s.svcCtx)
	return l.FileUpload(in)
}

func (s *StorageServer) FileDownload(ctx context.Context, in *storage.FileDownloadRequest) (*storage.FileDownloadResponse, error) {
	l := logic.NewFileDownloadLogic(ctx, s.svcCtx)
	return l.FileDownload(in)
}

func (s *StorageServer) FileDelete(ctx context.Context, in *storage.FileDeleteRequest) (*storage.FileDeleteResponse, error) {
	l := logic.NewFileDeleteLogic(ctx, s.svcCtx)
	return l.FileDelete(in)
}

func (s *StorageServer) FileInfo(ctx context.Context, in *storage.FileInfoRequest) (*storage.FileInfoResponse, error) {
	l := logic.NewFileInfoLogic(ctx, s.svcCtx)
	return l.FileInfo(in)
}

func (s *StorageServer) GetBussinessFiles(ctx context.Context, in *storage.GetBussinessFilesRequest) (*storage.GetBussinessFilesResponse, error) {
	l := logic.NewGetBussinessFilesLogic(ctx, s.svcCtx)
	return l.GetBussinessFiles(in)
}

func (s *StorageServer) DeleteBusinessFiles(ctx context.Context, in *storage.DeleteBusinessFilesRequest) (*storage.FileDeleteResponse, error) {
	l := logic.NewDeleteBusinessFilesLogic(ctx, s.svcCtx)
	return l.DeleteBusinessFiles(in)
}
