// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: achieve.proto

package server

import (
	"context"

	"github.com/bearllfleed/scholar-track/rpc/achieve/achieve"
	"github.com/bearllfleed/scholar-track/rpc/achieve/internal/logic/propertyservice"
	"github.com/bearllfleed/scholar-track/rpc/achieve/internal/svc"
)

type PropertyServiceServer struct {
	svcCtx *svc.ServiceContext
	achieve.UnimplementedPropertyServiceServer
}

func NewPropertyServiceServer(svcCtx *svc.ServiceContext) *PropertyServiceServer {
	return &PropertyServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PropertyServiceServer) CreateProperty(ctx context.Context, in *achieve.CreatePropertyReq) (*achieve.CreatePropertyResp, error) {
	l := propertyservicelogic.NewCreatePropertyLogic(ctx, s.svcCtx)
	return l.CreateProperty(in)
}

func (s *PropertyServiceServer) QueryPropertyDetail(ctx context.Context, in *achieve.QueryPropertyDetailReq) (*achieve.QueryPropertyDetailResp, error) {
	l := propertyservicelogic.NewQueryPropertyDetailLogic(ctx, s.svcCtx)
	return l.QueryPropertyDetail(in)
}

func (s *PropertyServiceServer) QueryPropertyList(ctx context.Context, in *achieve.QueryPropertyListReq) (*achieve.QueryPropertyListResp, error) {
	l := propertyservicelogic.NewQueryPropertyListLogic(ctx, s.svcCtx)
	return l.QueryPropertyList(in)
}

func (s *PropertyServiceServer) DeleteProperty(ctx context.Context, in *achieve.DeletePropertyReq) (*achieve.DeletePropertyResp, error) {
	l := propertyservicelogic.NewDeletePropertyLogic(ctx, s.svcCtx)
	return l.DeleteProperty(in)
}

func (s *PropertyServiceServer) UpdateProperty(ctx context.Context, in *achieve.UpdatePropertyReq) (*achieve.UpdatePropertyResp, error) {
	l := propertyservicelogic.NewUpdatePropertyLogic(ctx, s.svcCtx)
	return l.UpdateProperty(in)
}
