// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: system.proto

package server

import (
	"context"

	"github.com/bearllfleed/scholar-track/rpc/system/internal/logic/menuservice"
	"github.com/bearllfleed/scholar-track/rpc/system/internal/svc"
	"github.com/bearllfleed/scholar-track/rpc/system/system"
)

type MenuServiceServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedMenuServiceServer
}

func NewMenuServiceServer(svcCtx *svc.ServiceContext) *MenuServiceServer {
	return &MenuServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MenuServiceServer) CreateMenu(ctx context.Context, in *system.CreateMenuReq) (*system.CreateMenuResp, error) {
	l := menuservicelogic.NewCreateMenuLogic(ctx, s.svcCtx)
	return l.CreateMenu(in)
}

func (s *MenuServiceServer) QueryAllMenuTree(ctx context.Context, in *system.QueryAllMenuTreeReq) (*system.QueryAllMenuTreeResp, error) {
	l := menuservicelogic.NewQueryAllMenuTreeLogic(ctx, s.svcCtx)
	return l.QueryAllMenuTree(in)
}

func (s *MenuServiceServer) QueryRoleMenuTree(ctx context.Context, in *system.QueryRoleMenuTreeReq) (*system.QueryRoleMenuTreeResp, error) {
	l := menuservicelogic.NewQueryRoleMenuTreeLogic(ctx, s.svcCtx)
	return l.QueryRoleMenuTree(in)
}

func (s *MenuServiceServer) UpdateRoleMenu(ctx context.Context, in *system.UpdateRoleMenuReq) (*system.UpdateRoleMenuResp, error) {
	l := menuservicelogic.NewUpdateRoleMenuLogic(ctx, s.svcCtx)
	return l.UpdateRoleMenu(in)
}

func (s *MenuServiceServer) DeleteMenu(ctx context.Context, in *system.DeleteMenuReq) (*system.DeleteMenuResp, error) {
	l := menuservicelogic.NewDeleteMenuLogic(ctx, s.svcCtx)
	return l.DeleteMenu(in)
}

func (s *MenuServiceServer) QueryMenuDetail(ctx context.Context, in *system.QueryMenuDetailReq) (*system.QueryMenuDetailResp, error) {
	l := menuservicelogic.NewQueryMenuDetailLogic(ctx, s.svcCtx)
	return l.QueryMenuDetail(in)
}

func (s *MenuServiceServer) UpdateMenu(ctx context.Context, in *system.UpdateMenuReq) (*system.UpdateMenuResp, error) {
	l := menuservicelogic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}
