// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: system.proto

package dictionaryservice

import (
	"context"

	"github.com/bearllfleed/scholar-track/rpc/system/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddPolicyReq                    = system.AddPolicyReq
	AddPolicyResp                   = system.AddPolicyResp
	AddRoleReq                      = system.AddRoleReq
	AddRoleResp                     = system.AddRoleResp
	Api                             = system.Api
	ChangePasswordReq               = system.ChangePasswordReq
	ChangePasswordResp              = system.ChangePasswordResp
	CreateApiReq                    = system.CreateApiReq
	CreateApiResp                   = system.CreateApiResp
	CreateDictionaryDetailReq       = system.CreateDictionaryDetailReq
	CreateDictionaryDetailResp      = system.CreateDictionaryDetailResp
	CreateDictionaryReq             = system.CreateDictionaryReq
	CreateDictionaryResp            = system.CreateDictionaryResp
	CreateMenuReq                   = system.CreateMenuReq
	CreateMenuResp                  = system.CreateMenuResp
	DeleteApiReq                    = system.DeleteApiReq
	DeleteApiResp                   = system.DeleteApiResp
	DeleteDictionaryDetailReq       = system.DeleteDictionaryDetailReq
	DeleteDictionaryDetailResp      = system.DeleteDictionaryDetailResp
	DeleteDictionaryReq             = system.DeleteDictionaryReq
	DeleteDictionaryResp            = system.DeleteDictionaryResp
	DeleteMenuReq                   = system.DeleteMenuReq
	DeleteMenuResp                  = system.DeleteMenuResp
	DeleteRoleReq                   = system.DeleteRoleReq
	DeleteRoleResp                  = system.DeleteRoleResp
	DeleteUserReq                   = system.DeleteUserReq
	DeleteUserResp                  = system.DeleteUserResp
	Dictionary                      = system.Dictionary
	DictionaryDetail                = system.DictionaryDetail
	EnforceReq                      = system.EnforceReq
	EnforceResp                     = system.EnforceResp
	FindUserByUsernameReq           = system.FindUserByUsernameReq
	FindUserByUsernameResp          = system.FindUserByUsernameResp
	Menu                            = system.Menu
	Meta                            = system.Meta
	PolicyInfo                      = system.PolicyInfo
	QueryAllApiReq                  = system.QueryAllApiReq
	QueryAllApiResp                 = system.QueryAllApiResp
	QueryAllDictionaryDetailReq     = system.QueryAllDictionaryDetailReq
	QueryAllDictionaryDetailResp    = system.QueryAllDictionaryDetailResp
	QueryAllDictionaryReq           = system.QueryAllDictionaryReq
	QueryAllDictionaryResp          = system.QueryAllDictionaryResp
	QueryAllMenuTreeReq             = system.QueryAllMenuTreeReq
	QueryAllMenuTreeResp            = system.QueryAllMenuTreeResp
	QueryApiDetailReq               = system.QueryApiDetailReq
	QueryApiDetailResp              = system.QueryApiDetailResp
	QueryDictionaryDetailDetailReq  = system.QueryDictionaryDetailDetailReq
	QueryDictionaryDetailDetailResp = system.QueryDictionaryDetailDetailResp
	QueryDictionaryDetailReq        = system.QueryDictionaryDetailReq
	QueryDictionaryDetailResp       = system.QueryDictionaryDetailResp
	QueryDictionaryListReq          = system.QueryDictionaryListReq
	QueryDictionaryListResp         = system.QueryDictionaryListResp
	QueryMenuDetailReq              = system.QueryMenuDetailReq
	QueryMenuDetailResp             = system.QueryMenuDetailResp
	QueryRoleMenuTreeReq            = system.QueryRoleMenuTreeReq
	QueryRoleMenuTreeResp           = system.QueryRoleMenuTreeResp
	QueryRolePoliciesReq            = system.QueryRolePoliciesReq
	QueryRolePoliciesResp           = system.QueryRolePoliciesResp
	QuerySelfInfoReq                = system.QuerySelfInfoReq
	QuerySelfInfoResp               = system.QuerySelfInfoResp
	QueryUserDetailReq              = system.QueryUserDetailReq
	QueryUserDetailResp             = system.QueryUserDetailResp
	QueryUserListReq                = system.QueryUserListReq
	QueryUserListResp               = system.QueryUserListResp
	RegisterReq                     = system.RegisterReq
	RegisterResp                    = system.RegisterResp
	ResetPasswordReq                = system.ResetPasswordReq
	ResetPasswordResp               = system.ResetPasswordResp
	RoleResp                        = system.RoleResp
	RoleTreeListResp                = system.RoleTreeListResp
	RoleTreeReq                     = system.RoleTreeReq
	RoleTreeResp                    = system.RoleTreeResp
	Rule                            = system.Rule
	SetRolePoliciesReq              = system.SetRolePoliciesReq
	SetRolePoliciesResp             = system.SetRolePoliciesResp
	SetSelfInfoReq                  = system.SetSelfInfoReq
	SetSelfInfoResp                 = system.SetSelfInfoResp
	SetUserInfoReq                  = system.SetUserInfoReq
	SetUserInfoResp                 = system.SetUserInfoResp
	SetUserRoleReq                  = system.SetUserRoleReq
	SetUserRoleResp                 = system.SetUserRoleResp
	UpdateApiReq                    = system.UpdateApiReq
	UpdateApiResp                   = system.UpdateApiResp
	UpdateDictionaryDetailReq       = system.UpdateDictionaryDetailReq
	UpdateDictionaryDetailResp      = system.UpdateDictionaryDetailResp
	UpdateDictionaryReq             = system.UpdateDictionaryReq
	UpdateDictionaryResp            = system.UpdateDictionaryResp
	UpdateMenuReq                   = system.UpdateMenuReq
	UpdateMenuResp                  = system.UpdateMenuResp
	UpdateRoleMenuReq               = system.UpdateRoleMenuReq
	UpdateRoleMenuResp              = system.UpdateRoleMenuResp
	UpdateRoleReq                   = system.UpdateRoleReq
	UpdateRoleResp                  = system.UpdateRoleResp

	DictionaryService interface {
		CreateDictionary(ctx context.Context, in *CreateDictionaryReq, opts ...grpc.CallOption) (*CreateDictionaryResp, error)
		QueryDictionaryDetail(ctx context.Context, in *QueryDictionaryDetailReq, opts ...grpc.CallOption) (*QueryDictionaryDetailResp, error)
		QueryAllDictionary(ctx context.Context, in *QueryAllDictionaryReq, opts ...grpc.CallOption) (*QueryAllDictionaryResp, error)
		UpdateDictionary(ctx context.Context, in *UpdateDictionaryReq, opts ...grpc.CallOption) (*UpdateDictionaryResp, error)
		DeleteDictionary(ctx context.Context, in *DeleteDictionaryReq, opts ...grpc.CallOption) (*DeleteDictionaryResp, error)
		CreateDictionaryDetail(ctx context.Context, in *CreateDictionaryDetailReq, opts ...grpc.CallOption) (*CreateDictionaryDetailResp, error)
		QueryDictionaryDetailDetail(ctx context.Context, in *QueryDictionaryDetailDetailReq, opts ...grpc.CallOption) (*QueryDictionaryDetailDetailResp, error)
		QueryAllDictionaryDetail(ctx context.Context, in *QueryAllDictionaryDetailReq, opts ...grpc.CallOption) (*QueryAllDictionaryDetailResp, error)
		UpdateDictionaryDetail(ctx context.Context, in *UpdateDictionaryDetailReq, opts ...grpc.CallOption) (*UpdateDictionaryDetailResp, error)
		DeleteDictionaryDetail(ctx context.Context, in *DeleteDictionaryDetailReq, opts ...grpc.CallOption) (*DeleteDictionaryDetailResp, error)
		QueryDictionaryList(ctx context.Context, in *QueryDictionaryListReq, opts ...grpc.CallOption) (*QueryDictionaryListResp, error)
	}

	defaultDictionaryService struct {
		cli zrpc.Client
	}
)

func NewDictionaryService(cli zrpc.Client) DictionaryService {
	return &defaultDictionaryService{
		cli: cli,
	}
}

func (m *defaultDictionaryService) CreateDictionary(ctx context.Context, in *CreateDictionaryReq, opts ...grpc.CallOption) (*CreateDictionaryResp, error) {
	client := system.NewDictionaryServiceClient(m.cli.Conn())
	return client.CreateDictionary(ctx, in, opts...)
}

func (m *defaultDictionaryService) QueryDictionaryDetail(ctx context.Context, in *QueryDictionaryDetailReq, opts ...grpc.CallOption) (*QueryDictionaryDetailResp, error) {
	client := system.NewDictionaryServiceClient(m.cli.Conn())
	return client.QueryDictionaryDetail(ctx, in, opts...)
}

func (m *defaultDictionaryService) QueryAllDictionary(ctx context.Context, in *QueryAllDictionaryReq, opts ...grpc.CallOption) (*QueryAllDictionaryResp, error) {
	client := system.NewDictionaryServiceClient(m.cli.Conn())
	return client.QueryAllDictionary(ctx, in, opts...)
}

func (m *defaultDictionaryService) UpdateDictionary(ctx context.Context, in *UpdateDictionaryReq, opts ...grpc.CallOption) (*UpdateDictionaryResp, error) {
	client := system.NewDictionaryServiceClient(m.cli.Conn())
	return client.UpdateDictionary(ctx, in, opts...)
}

func (m *defaultDictionaryService) DeleteDictionary(ctx context.Context, in *DeleteDictionaryReq, opts ...grpc.CallOption) (*DeleteDictionaryResp, error) {
	client := system.NewDictionaryServiceClient(m.cli.Conn())
	return client.DeleteDictionary(ctx, in, opts...)
}

func (m *defaultDictionaryService) CreateDictionaryDetail(ctx context.Context, in *CreateDictionaryDetailReq, opts ...grpc.CallOption) (*CreateDictionaryDetailResp, error) {
	client := system.NewDictionaryServiceClient(m.cli.Conn())
	return client.CreateDictionaryDetail(ctx, in, opts...)
}

func (m *defaultDictionaryService) QueryDictionaryDetailDetail(ctx context.Context, in *QueryDictionaryDetailDetailReq, opts ...grpc.CallOption) (*QueryDictionaryDetailDetailResp, error) {
	client := system.NewDictionaryServiceClient(m.cli.Conn())
	return client.QueryDictionaryDetailDetail(ctx, in, opts...)
}

func (m *defaultDictionaryService) QueryAllDictionaryDetail(ctx context.Context, in *QueryAllDictionaryDetailReq, opts ...grpc.CallOption) (*QueryAllDictionaryDetailResp, error) {
	client := system.NewDictionaryServiceClient(m.cli.Conn())
	return client.QueryAllDictionaryDetail(ctx, in, opts...)
}

func (m *defaultDictionaryService) UpdateDictionaryDetail(ctx context.Context, in *UpdateDictionaryDetailReq, opts ...grpc.CallOption) (*UpdateDictionaryDetailResp, error) {
	client := system.NewDictionaryServiceClient(m.cli.Conn())
	return client.UpdateDictionaryDetail(ctx, in, opts...)
}

func (m *defaultDictionaryService) DeleteDictionaryDetail(ctx context.Context, in *DeleteDictionaryDetailReq, opts ...grpc.CallOption) (*DeleteDictionaryDetailResp, error) {
	client := system.NewDictionaryServiceClient(m.cli.Conn())
	return client.DeleteDictionaryDetail(ctx, in, opts...)
}

func (m *defaultDictionaryService) QueryDictionaryList(ctx context.Context, in *QueryDictionaryListReq, opts ...grpc.CallOption) (*QueryDictionaryListResp, error) {
	client := system.NewDictionaryServiceClient(m.cli.Conn())
	return client.QueryDictionaryList(ctx, in, opts...)
}
