// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: achieve.proto

package server

import (
	"context"

	"github.com/bearllflee/scholar-track/rpc/achieve/achieve"
	"github.com/bearllflee/scholar-track/rpc/achieve/internal/logic/achieveservice"
	"github.com/bearllflee/scholar-track/rpc/achieve/internal/svc"
)

type AchieveServiceServer struct {
	svcCtx *svc.ServiceContext
	achieve.UnimplementedAchieveServiceServer
}

func NewAchieveServiceServer(svcCtx *svc.ServiceContext) *AchieveServiceServer {
	return &AchieveServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AchieveServiceServer) UploadAchieve(ctx context.Context, in *achieve.UploadAchieveReq) (*achieve.UploadAchieveResp, error) {
	l := achieveservicelogic.NewUploadAchieveLogic(ctx, s.svcCtx)
	return l.UploadAchieve(in)
}

func (s *AchieveServiceServer) DeleteAchieve(ctx context.Context, in *achieve.DeleteAchieveReq) (*achieve.DeleteAchieveResp, error) {
	l := achieveservicelogic.NewDeleteAchieveLogic(ctx, s.svcCtx)
	return l.DeleteAchieve(in)
}
