// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: system.proto

package server

import (
	"context"

	"github.com/bearllfleed/scholar-track/rpc/system/internal/logic/dictionaryservice"
	"github.com/bearllfleed/scholar-track/rpc/system/internal/svc"
	"github.com/bearllfleed/scholar-track/rpc/system/system"
)

type DictionaryServiceServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedDictionaryServiceServer
}

func NewDictionaryServiceServer(svcCtx *svc.ServiceContext) *DictionaryServiceServer {
	return &DictionaryServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *DictionaryServiceServer) CreateDictionary(ctx context.Context, in *system.CreateDictionaryReq) (*system.CreateDictionaryResp, error) {
	l := dictionaryservicelogic.NewCreateDictionaryLogic(ctx, s.svcCtx)
	return l.CreateDictionary(in)
}

func (s *DictionaryServiceServer) QueryDictionaryDetail(ctx context.Context, in *system.QueryDictionaryDetailReq) (*system.QueryDictionaryDetailResp, error) {
	l := dictionaryservicelogic.NewQueryDictionaryDetailLogic(ctx, s.svcCtx)
	return l.QueryDictionaryDetail(in)
}

func (s *DictionaryServiceServer) QueryAllDictionary(ctx context.Context, in *system.QueryAllDictionaryReq) (*system.QueryAllDictionaryResp, error) {
	l := dictionaryservicelogic.NewQueryAllDictionaryLogic(ctx, s.svcCtx)
	return l.QueryAllDictionary(in)
}

func (s *DictionaryServiceServer) UpdateDictionary(ctx context.Context, in *system.UpdateDictionaryReq) (*system.UpdateDictionaryResp, error) {
	l := dictionaryservicelogic.NewUpdateDictionaryLogic(ctx, s.svcCtx)
	return l.UpdateDictionary(in)
}

func (s *DictionaryServiceServer) DeleteDictionary(ctx context.Context, in *system.DeleteDictionaryReq) (*system.DeleteDictionaryResp, error) {
	l := dictionaryservicelogic.NewDeleteDictionaryLogic(ctx, s.svcCtx)
	return l.DeleteDictionary(in)
}

func (s *DictionaryServiceServer) CreateDictionaryDetail(ctx context.Context, in *system.CreateDictionaryDetailReq) (*system.CreateDictionaryDetailResp, error) {
	l := dictionaryservicelogic.NewCreateDictionaryDetailLogic(ctx, s.svcCtx)
	return l.CreateDictionaryDetail(in)
}

func (s *DictionaryServiceServer) QueryDictionaryDetailDetail(ctx context.Context, in *system.QueryDictionaryDetailDetailReq) (*system.QueryDictionaryDetailDetailResp, error) {
	l := dictionaryservicelogic.NewQueryDictionaryDetailDetailLogic(ctx, s.svcCtx)
	return l.QueryDictionaryDetailDetail(in)
}

func (s *DictionaryServiceServer) QueryAllDictionaryDetail(ctx context.Context, in *system.QueryAllDictionaryDetailReq) (*system.QueryAllDictionaryDetailResp, error) {
	l := dictionaryservicelogic.NewQueryAllDictionaryDetailLogic(ctx, s.svcCtx)
	return l.QueryAllDictionaryDetail(in)
}

func (s *DictionaryServiceServer) UpdateDictionaryDetail(ctx context.Context, in *system.UpdateDictionaryDetailReq) (*system.UpdateDictionaryDetailResp, error) {
	l := dictionaryservicelogic.NewUpdateDictionaryDetailLogic(ctx, s.svcCtx)
	return l.UpdateDictionaryDetail(in)
}

func (s *DictionaryServiceServer) DeleteDictionaryDetail(ctx context.Context, in *system.DeleteDictionaryDetailReq) (*system.DeleteDictionaryDetailResp, error) {
	l := dictionaryservicelogic.NewDeleteDictionaryDetailLogic(ctx, s.svcCtx)
	return l.DeleteDictionaryDetail(in)
}

func (s *DictionaryServiceServer) QueryDictionaryList(ctx context.Context, in *system.QueryDictionaryListReq) (*system.QueryDictionaryListResp, error) {
	l := dictionaryservicelogic.NewQueryDictionaryListLogic(ctx, s.svcCtx)
	return l.QueryDictionaryList(in)
}
