@split = ----WebKitFormBoundary7MA4YWxkTrZu0gW

### @name login
POST {{host}}/user/login HTTP/1.1
Content-Type: application/json

{
    "username": "1900300311",
    "password": "123123123"
}

POST {{host}}/user/register HTTP/1.1
Content-Type: application/json

{
    "username": "1900300311",
    "password": "123123123",
    "email": "2923780891@qq.com",
    "phone": "13217735989",
    "nickname": "狗熊岭在逃熊二",
    "roleId": 888,
    "gender": 1,
    "major": "软件工程",
    "grade": "2019",
    "college": "计算机与信息安全学院",
    "realname": "丁元广",
    "class": "19003003"
}

